### ISSUE TITLE
Expose ICUCollationKeyAnalyzer

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-analysis-icu#28]
The `icu_collation` filter is deprecated, and should be replaced by the ICUCollationKeyAnalyzer (exposed as the `icu_collation_key` analyzer).   However, I would recommend making some changes at the same time:

Use `locale` instead of `language`/ `country`/ `variant`, eg : 

* `en`
* `en_US`
* `de_DE@collation=phonebook`
* `zh_CN@collation=pinyin`

Keep `strength`, `rules`, `decomposition`, `alternate`, `case_level`, `case_first`, `numeric`, `variable_top`.

It looks like `hiraganaQuaternaryMode` is no longer used by ICU (but not sure about that)

If no locale is specified, then it should default to ULocale.ROOT (ie DUCET) rather than what it does currently, which is to default to the current locale active in the JVM.

Finally, it would be good to add the `truncate` token filter into the analyzer so that users can truncate a potentially long original string into (eg) the first 10 characters, so that it uses less memory.

NOTE: We need to check that binary sorting is supported correctly in Elasticsearch.  @jpountz thinks this is the case, but needs to be confirmed.

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#13149
