### ISSUE TITLE
Add icu_collation field type

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-analysis-icu#29]
Collation fields are used just for sorting - they don't need to be indexed or stored.  

We can use a new `icu_collation_key` field type which accepts the same parameters as the ICUCollationKeyAnalyzer, and isn't indexed but stores its values as doc values, using  ICUCollationDocValuesField.

This field type would need to serialize its sort keys as base64 for inclusion in the JSON response.

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#13148
