### ISSUE TITLE
Match term with ICU collation fails

### ISSUE THREAD

**Issue by malthe** [elastic/elasticsearch-analysis-icu#52]
I have configured an analyzer with ``keyword`` tokenization and the ``icu_collation`` filter. This field is usable to sort results, but I can't seem to use the same field for exact term matching:
```json
{
  "query": {
    "filtered": {
      "filter": {
        "term": {
           "<field>": "<value>"
        }
      }
    }
  }
}
```
Is this expected behavior or does term filtering need special configuration?

**Comment by shwetaskatdare** [comment]
I have the exact same issue. I have a field of type string which holds numbers ("1234"). The icu_collation analyzer works for sorting the but when I try to use a term filter query it doesn't work.

**Comment by dadoonet** [comment]
Can you guys send a full reproduction script?

**Comment by dadoonet** [comment]
No move on this. Closing. Feel free to reopen this issue in elasticsearch repository where this plugin is now maintained.
